image: conanio/gcc7
variables:
  CHANNEL: stable
  GITLAB_PACKAGE_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/conan
  CONAN_USER_HOME: ${CI_PROJECT_DIR}/.conan/
  CONAN_LOGIN_USERNAME: ci_user
  CONAN_PASSWORD: ${CI_JOB_TOKEN}
  SAST_FLAWFINDER_LEVEL: 0

cache:
  paths:
    - .conan/
    - build/
    - test_package/build/

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - source ./bin/env.sh
    - REFERENCE=${PACKAGE_NAME}/${PACKAGE_VERSION}@${CI_PROJECT_PATH//\//+}/${CHANNEL}
  script:
    - conan remote add gitlab ${GITLAB_PACKAGE_URL} --force
    #    - conan remove ${REFERENCE} --remote=gitlab --force
    - bash ./bin/clean.sh
    - bash ./bin/build.sh -t Release

fuzz:
  image: aflplusplus/aflplusplus
  stage: test
  dependencies:
    - build
  allow_failure: true
  before_script:
    - apt update -y
    - apt install -y python3 python3-pip cmake gcc g++
    - pip install conan
  script:
    - bash ./bin/build.sh -t Debug
    - exit 1

create_package:
  stage: deploy
  dependencies:
    - build
  before_script:
    - source ./bin/env.sh
    - REFERENCE=${PACKAGE_NAME}/${PACKAGE_VERSION}@${CI_PROJECT_PATH//\//+}/${CHANNEL}
    - echo upload ${REFERENCE} to ${GITLAB_PACKAGE_URL}
  script:
    - bash ./bin/package.sh
    - conan upload ${REFERENCE} --all --remote=gitlab --confirm --force
