image: conanio/gcc7
variables:
  CONAN_REGISTORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/conan
  CONAN_LOGIN_USERNAME: ci_user
  CONAN_PASSWORD: ${CI_JOB_TOKEN}
  SAST_FLAWFINDER_LEVEL: 0

cache:
  paths:
    - .conan/
    - build/
    - test_package/build/

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    # - conan remote add gitlab ${CONAN_REGISTORY_URL} --force
    #    - conan remove ${PACKAGE_REFERENCE} --remote=gitlab --force
    - bash ./bin/clean.sh
    - bash ./bin/build.sh -t Release

fuzz:
  image: aflplusplus/aflplusplus
  stage: test
  dependencies:
    - build
  allow_failure: true
  before_script:
    - apt update -y
    - apt install -y python3 python3-pip cmake gcc g++
    - pip install conan
  script:
    - bash ./bin/build.sh -t Debug
    - exit 1

create_package:
  stage: deploy
  dependencies:
    - build
  script:
    - bash ./bin/package.sh
    - bash ./bin/upload.sh -t ${CONAN_REGISTORY_URL}
    - cp test/build/**/bin/*.xml .
  artifacts:
    when: always
    reports:
      junit: CUnitAutomated-Results.xml
