name: conan

inputs:
  python-version:
    default: "3.8"
    required: false
    description: "version of python"
  poetry-version:
    default: "1.1.11"
    required: false
    description: "version of poetry"
  cache-key:
    required: true
    description: "cache key for poetry"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - uses: actions/cache@v2
      id: poetry_cache_id
      with:
        path: .venv
        key: ${{ inputs.cache-key }}
    - name: install conan
      if: steps.poetry_cache_id.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry install --no-interaction --no-root
