name: conan ci

on:
  push:

env:
  CHANNEL: stable

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.11]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init conan
        uses: ./.github/actions/init-conan
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}
          cache-key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/cache@v2
        id: conan_cache_id
        with:
          path: .conan
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.py') }}
      - name: build
        run: |
          . .venv/bin/activate
          ./bin/build.sh -t Release
      - name: package 
        run: |
          . .venv/bin/activate
          ./bin/package.sh
      - name: upload cunit-xml
        uses: actions/upload-artifact@v2.2.4
        with:
          name: cunit-xml
          path: ./test/build/**/bin/*.xml
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.11]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install fuzzer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y afl++
      - name: init conan
        uses: ./.github/actions/init-conan
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}
          cache-key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/cache@v2
        id: conan_cache_id
        with:
          path: .conan
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.py') }}
      - name: fuzzing
        shell: bash
        run: |
          . .venv/bin/activate
          ./bin/build.sh -t Debug
